# Generated by Django 5.2.7 on 2025-10-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('serving_size', models.CharField(max_length=100)),
                ('cook_time', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('equipment', models.TextField()),
                ('instructions', models.TextField()),
            ],
        ),
    ]
