# Generated by Django 5.2.7 on 2025-11-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_remove_recipe_ingredients_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tips',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
