# Generated by Django 5.2.7 on 2025-11-12 10:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_favourites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favourites',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='favourites',
            unique_together={('user', 'recipe')},
        ),
    ]
