# Generated by Django 5.2.7 on 2025-11-20 05:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_alter_favourites_recipe_alter_favourites_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='favourites',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favourites',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='favourites',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='recipe',
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at'], 'permissions': [('approve_recipe', 'Can approve pending recipes'), ('flag_recipe', 'Can flag inappropriate recipes')], 'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Author of the recipe', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='average_rating',
            field=models.FloatField(default=0.0, help_text='Average rating (0-5)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, help_text='Recipe description or introduction'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Difficulty level', max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured image for the recipe', null=True, upload_to='recipes/featured/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutrition_info',
            field=models.JSONField(blank=True, default=dict, help_text='Nutrition info: {calories, protein_g, carbs_g, fat_g, fiber_g}'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(default=0, help_text='Preparation time in minutes'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the title', unique=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0, help_text='Total number of ratings'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional YouTube or video tutorial link'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times recipe was viewed'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='visibility',
            field=models.CharField(choices=[('draft', 'Draft'), ('private', 'Private'), ('pending', 'Pending Review'), ('public', 'Public')], default='draft', help_text='Recipe visibility', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.PositiveIntegerField(help_text='Cooking time in minutes', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='equipment',
            field=models.JSONField(blank=True, default=list, help_text='List of required equipment'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.JSONField(default=list, help_text='Step-by-step instructions as JSON array'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='serving_size',
            field=models.PositiveIntegerField(default=4, help_text='Number of servings', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tips',
            field=models.TextField(blank=True, default='null', help_text='Chef tips and variations'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(help_text='Recipe title', max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, blank=True),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='recipe',
            table='recipes_recipe',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Comment content')),
                ('is_spam', models.BooleanField(default=False, help_text='Flag for spam detection')),
                ('is_approved', models.BooleanField(default=True, help_text='Whether comment is approved for display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(help_text='Recipe being commented on', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipe.recipe')),
                ('user', models.ForeignKey(help_text='User who commented', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'recipes_comment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingredient name', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity of ingredient', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilogram'), ('ml', 'Milliliter'), ('l', 'Liter'), ('oz', 'Ounce'), ('lb', 'Pound'), ('cup', 'Cup'), ('tbsp', 'Tablespoon'), ('tsp', 'Teaspoon'), ('pint', 'Pint'), ('units', 'Units'), ('whole', 'Whole'), ('to_taste', 'To taste')], default='units', help_text='Unit of measurement', max_length=20)),
                ('type', models.CharField(choices=[('main', 'Main Ingredient'), ('spice', 'Spice'), ('seasoning', 'Seasoning'), ('garnish', 'Garnish'), ('other', 'Other')], default='main', help_text='Type of ingredient', max_length=20)),
                ('notes', models.TextField(blank=True, help_text="Optional notes (e.g., 'finely diced', 'room temperature')")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(help_text='Recipe this ingredient belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe.recipe')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'db_table': 'recipes_ingredient',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Rating (1-5 stars)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, help_text='Optional written review')),
                ('is_spam', models.BooleanField(default=False, help_text='Flag for spam detection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(help_text='Recipe being rated', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='recipe.recipe')),
                ('user', models.ForeignKey(help_text='User who rated', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'db_table': 'recipes_rating',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Recipe image', upload_to='recipes/images/')),
                ('image_type', models.CharField(choices=[('featured', 'Featured Image'), ('step', 'Step Image'), ('gallery', 'Gallery Image')], default='gallery', help_text='Type of image', max_length=20)),
                ('step_number', models.PositiveIntegerField(blank=True, help_text='Step number if this is a step image', null=True)),
                ('caption', models.TextField(blank=True, help_text='Image caption or description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(help_text='Recipe this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recipe.recipe')),
            ],
            options={
                'verbose_name': 'Recipe Image',
                'verbose_name_plural': 'Recipe Images',
                'db_table': 'recipes_recipe_image',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(help_text='Version number')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.JSONField()),
                ('ingredients_snapshot', models.JSONField(help_text='JSON snapshot of ingredients at this version')),
                ('change_summary', models.TextField(blank=True, help_text='Description of changes in this version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_edits', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(help_text='Recipe this version belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='recipe.recipe')),
            ],
            options={
                'verbose_name': 'Recipe Version',
                'verbose_name_plural': 'Recipe Versions',
                'db_table': 'recipes_recipe_version',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Tag or category name (e.g., 'Vegan', 'Italian', 'Gluten-Free')", max_length=100, unique=True)),
                ('type', models.CharField(choices=[('tag', 'Tag'), ('category', 'Category'), ('dietary', 'Dietary Restriction'), ('cuisine', 'Cuisine')], default='tag', help_text='Type of tag', max_length=20)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the name', unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the tag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'recipes_tag',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='recipes_tag_slug_3ea026_idx'), models.Index(fields=['type'], name='recipes_tag_type_ef8eda_idx')],
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for this recipe', related_name='recipes', to='recipe.tag'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['author', '-created_at'], name='recipes_rec_author__0ddfe9_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['visibility', '-created_at'], name='recipes_rec_visibil_6fad0c_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['slug'], name='recipes_rec_slug_412256_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['-average_rating'], name='recipes_rec_average_edefee_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['difficulty'], name='recipes_rec_difficu_33131c_idx'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Favourites',
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['recipe', '-created_at'], name='recipes_com_recipe__d91579_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user'], name='recipes_com_user_id_36825b_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_spam', 'is_approved'], name='recipes_com_is_spam_686378_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['recipe'], name='recipes_ing_recipe__fac781_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['name'], name='recipes_ing_name_164c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['recipe'], name='recipes_rat_recipe__263c1e_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user'], name='recipes_rat_user_id_05e6e5_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rating'], name='recipes_rat_rating_8a4c09_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'recipe')},
        ),
        migrations.AddIndex(
            model_name='recipeimage',
            index=models.Index(fields=['recipe', 'image_type'], name='recipes_rec_recipe__a1da14_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeversion',
            index=models.Index(fields=['recipe', '-version_number'], name='recipes_rec_recipe__98b0a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recipeversion',
            unique_together={('recipe', 'version_number')},
        ),
    ]
